project:
  type: website

website:
  title: "quarto-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    contents:
      - "extra-stuff/file.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true